routes/admin.php
<?php

Route::resource('customer', 'CustomerController');

Route::prefix('customer/{customer}')->group(function () {
    Route::resource('product-tag-category', 'ProductTagCategoryController');
    Route::resource('article-category', 'ArticleCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('media-type', 'MediaTypeController');
    Route::resource('content-type', 'ContentTypeController');

    Route::get('product-setting', 'ProductSettingController@index')->name('product-setting.index');
    Route::post('product-setting', 'ProductSettingController@save')->name('product-setting.save');

    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::post('contact', 'ContactController@save')->name('contact.save');
});

routes/web.php
<?php

// Auth
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

// Control Panel
Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    ctf0\MediaManager\MediaRoutes::routes();

    Route::namespace('Features')->group(base_path('routes/features.php'));
    Route::namespace('Admin')->middleware('admin.domain')->group(base_path('routes/admin.php'));
});

resources/views/admin/page/create.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '頁面生產' => route('page.index', $customer),
        '新增',
    ]])

    <div class="card m-4">
        <div class="card-body">
            <form method="POST" action="{{ route('page.store', $customer) }}">
                {{ csrf_field() }}

                @include('admin.page._form')

                <button type="submit" class="btn btn-lg btn-primary btn-block">儲存</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/page/edit.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '頁面生產' => route('page.index', $customer),
        '編輯',
    ]])

    <div class="card m-4">
        <div class="card-body">
            <form method="POST" action="{{ route('page.update', [$customer, $page]) }}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                @include('admin.page._form')

                <button type="submit" class="btn btn-lg btn-primary btn-block">儲存</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/page/index.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '頁面生產',
    ]])

    <table-component :fields="{{ $fields }}"
                     base-url="{{ route('page.index', $customer) }}"
                     api-url="{{ route('api.admin.page.get', $customer) }}"
                     api-token="{{ auth()->user()->api_token }}"
                     :can-copy="false">
    </table-component>
@endsection