routes/admin.php
<?php

Route::resource('customer', 'CustomerController');

Route::prefix('customer/{customer}')->group(function () {
    Route::resource('product-tag-category', 'ProductTagCategoryController');
    Route::resource('article-category', 'ArticleCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('media-type', 'MediaTypeController');
    Route::resource('content-type', 'ContentTypeController');

    Route::get('product-setting', 'ProductSettingController@index')->name('product-setting.index');
    Route::post('product-setting', 'ProductSettingController@save')->name('product-setting.save');

    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::post('contact', 'ContactController@save')->name('contact.save');
});

routes/web.php
<?php

// Auth
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

// Control Panel
Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    ctf0\MediaManager\MediaRoutes::routes();

    Route::namespace('Features')->group(base_path('routes/features.php'));
    Route::namespace('Admin')->middleware('admin.domain')->group(base_path('routes/admin.php'));
});

resources/views/layouts/admin/sidebar/superadmin/customer.blade.php
<li class="nav-item">
    <a class="nav-link {{ active(['customer.index', 'customer.create', 'customer.edit']) }}" href="{{ route('customer.index') }}">
        <i class="nav-icon fa fa-list"></i> Customers
    </a>
</li>

resources/views/layouts/admin/sidebar/superadmin/customer_list.blade.php
@foreach ($customerGroup as $prefix => $customers)
<li class="nav-title border-center pb-0" data-toggle="collapse" data-target="#collapse{{ $prefix }}">
    <span class="">{{ $prefix }}</span>
</li>
<div class="collapse  {{ $customers['active'] ? 'show' : '' }}" id="collapse{{ $prefix }}">
    @foreach ($customers['items'] as $customer)
    <li class="nav-item nav-dropdown {{ active('customer/'. $customer->id . '/*', 'open') }}">
        <a class="nav-link nav-dropdown-toggle" href="#">
            <i class="nav-icon fa fa-users"></i> {{ $customer->domain }}
        </a>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('page.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 頁面產生
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('product-setting.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 產品設定
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('product-tag-category.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 產品標籤類別
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('article-category.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 文章類別
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('media-type.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 媒體類別
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('content-type.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 內容產生
                </a>
            </li>
        </ul>

        <ul class="nav-dropdown-items">
            <li class="nav-item">
                <a class="nav-link" href="{{ route('contact.index', $customer) }}">
                    <i class="nav-icon fa fa-fw ml-3"></i> 聯絡設定
                </a>
            </li>
        </ul>
    </li>
    @endforeach
</div>
@endforeach