routes/admin.php
<?php

Route::resource('customer', 'CustomerController');

Route::prefix('customer/{customer}')->group(function () {
    Route::resource('product-tag-category', 'ProductTagCategoryController');
    Route::resource('article-category', 'ArticleCategoryController');
    Route::resource('page', 'PageController');
    Route::resource('media-type', 'MediaTypeController');
    Route::resource('content-type', 'ContentTypeController');

    Route::get('product-setting', 'ProductSettingController@index')->name('product-setting.index');
    Route::post('product-setting', 'ProductSettingController@save')->name('product-setting.save');

    Route::get('contact', 'ContactController@index')->name('contact.index');
    Route::post('contact', 'ContactController@save')->name('contact.save');
});

routes/web.php
<?php

// Auth
Route::namespace('Auth')->group(function () {
    Route::get('login', 'LoginController@showLoginForm')->name('login');
    Route::post('login', 'LoginController@login');
    Route::get('logout', 'LoginController@logout')->name('logout');
});

// Control Panel
Route::middleware('auth')->group(function () {
    Route::get('/', 'HomeController@index')->name('home');

    ctf0\MediaManager\MediaRoutes::routes();

    Route::namespace('Features')->group(base_path('routes/features.php'));
    Route::namespace('Admin')->middleware('admin.domain')->group(base_path('routes/admin.php'));
});

app/Models/ProductTagCategory.php
<?php

namespace App\Models;


use Illuminate\Database\Eloquent\Model;

class ProductTagCategory extends Model
{
    protected $guarded = ['id'];

    /** relations */
    public function customer()
    {
        return $this->belongsTo(Customer::class);
    }

    public function tags()
    {
        return $this->hasMany('App\Models\ProductTag', 'category_id', 'id')->withoutGlobalScopes();
    }
}

app/Http/Controllers/Admin/ProductTagCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Customer;
use App\Models\ProductTagCategory;
use App\Writers\ProductTagCategoryWriter;
use Illuminate\Http\Request;

class ProductTagCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param Customer $customer
     * @return \Illuminate\Http\Response
     */
    public function index(Customer $customer)
    {
        $fields = collect([
            ['key' => 'id', 'label' => 'ID', 'sortable' => 'true'],
            ['key' => 'name', 'label' => '名稱', 'sortable' => 'true'],
            ['key' => 'type', 'label' => '類型', 'sortable' => 'true'],
            ['key' => 'multiple', 'label' => '多選', 'formatter' => 'formatBoolean', 'sortable' => 'true'],
            ['key' => 'status', 'label' => '狀態', 'sortable' => 'true'],
        ]);

        return view('admin.product_tag_category.index', compact('customer', 'fields'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param Customer $customer
     * @return \Illuminate\Http\Response

     */
    public function create(Customer $customer)
    {
        $productTagCategory = new ProductTagCategory;

        return view('admin.product_tag_category.create', compact('customer', 'productTagCategory'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Customer $customer
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, Customer $customer)
    {
        $writer = new ProductTagCategoryWriter($customer);
        $writer->store($request);

        flash('新增完成')->success();

        return redirect()->route('product-tag-category.index', $customer);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\ProductTagCategory  $productTagCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ProductTagCategory $productTagCategory)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Customer $customer
     * @param  \App\Models\ProductTagCategory $productTagCategory
     * @return \Illuminate\Http\Response

     */
    public function edit(Customer $customer, ProductTagCategory $productTagCategory)
    {
        return view('admin.product_tag_category.edit', compact('customer', 'productTagCategory'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param Customer $customer
     * @param  \App\Models\ProductTagCategory $productTagCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Customer $customer, ProductTagCategory $productTagCategory)
    {
        $writer = new ProductTagCategoryWriter($customer);
        $writer->for($productTagCategory)->store($request);

        flash('新增完成')->success();

        return redirect()->route('product-tag-category.index', $customer);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Customer $customer
     * @param  \App\Models\ProductTagCategory $productTagCategory
     * @return \Illuminate\Http\Response

     */
    public function destroy(Customer $customer, ProductTagCategory $productTagCategory)
    {
        try {
            $productTagCategory->delete();

            $type = 'success';
            $text = '刪除成功';
        } catch (\Exception $e) {
            $type = 'error';
            $text = $e->getMessage();
        }

        return $this->notifyAndRedirect($type, $text, route('product-tag-category.index', $customer));
    }
}

app/Http/Controllers/Api/Admin/ProductTagCategoryController.php
<?php


namespace App\Http\Controllers\Api\Admin;



use App\Http\Controllers\Api\Controller;
use App\Models\Customer;
use App\Models\ProductTagCategory;
use Illuminate\Http\Request;

class ProductTagCategoryController extends Controller
{
    public function get(Customer $customer, Request $request)
    {
        $categories = ProductTagCategory::where('customer_id', $customer->id)->get();

        if (!$categories) {
            return $this->failResponse('Categories not found.');
        }

        return $this->successResponse($categories);
    }

    public function status(Customer $customer, $id, Request $request)
    {
        $category = ProductTagCategory::find($id);

        if (!isset($request->status) || !$category) {
            return $this->failResponse('Error');
        }

        $category->status = $request->status;
        $category->save();

        return $this->successResponse([
            'type' => 'success',
            'text' => '狀態調整成功',
        ]);
    }
}

resources/views/admin/product_tag_category/_form.blade.php
<div class="form-group row">
    <label class="col-sm-2 col-form-label">名稱 @requiredInput</label>
    <div class="col-sm-10">
        <input type="text" name="name"
                class="form-control @formValidClass('name')"
                required
                value="{{ old('name', $productTagCategory->name) }}" />

        @include('partials.form.invalid-feedback', ['field' => 'name'])
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">類型 @requiredInput</label>
    <div class="col-sm-10">
        <input type="text" name="type"
               class="form-control @formValidClass('type')"
               required
               value="{{ old('type', $productTagCategory->type) }}" />

        @include('partials.form.invalid-feedback', ['field' => 'type'])
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">多選 @requiredInput</label>
    <div class="col-sm-10">
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="multiple" id="multiple1" value="1" checked>
            <label class="form-check-label" for="multiple1">是</label>
        </div>
        <div class="form-check form-check-inline">
            <input class="form-check-input" type="radio" name="multiple" id="multiple2" value="0" @if ($productTagCategory->multiple === 0) checked @endif>
            <label class="form-check-label" for="multiple2">否</label>
        </div>

        @include('partials.form.invalid-feedback', ['field' => 'multiple'])
    </div>
</div>

<div class="form-group row">
    <label class="col-sm-2 col-form-label">排序</label>
    <div class="col-sm-10">
        <input type="number" name="sort"
               class="form-control @formValidClass('sort')"
               value="{{ old('sort', $productTagCategory->sort) }}" />

        @include('partials.form.invalid-feedback', ['field' => 'sort'])
    </div>
</div>

resources/views/admin/product_tag_category/create.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '產品標籤管理' => route('product-tag-category.index', $customer),
        '新增',
    ]])

    <div class="card m-4">
        <div class="card-body">
            <form method="POST" action="{{ route('product-tag-category.store', $customer) }}">
                {{ csrf_field() }}

                @include('admin.product_tag_category._form')

                <button type="submit" class="btn btn-lg btn-primary btn-block">儲存</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/product_tag_category/edit.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '產品標籤管理' => route('product-tag-category.index', $customer),
        '編輯',
    ]])

    <div class="card m-4">
        <div class="card-body">
            <form method="POST" action="{{ route('product-tag-category.update', [$customer, $productTagCategory]) }}">
                {{ csrf_field() }}
                {{ method_field('PUT') }}

                @include('admin.product_tag_category._form')

                <button type="submit" class="btn btn-lg btn-primary btn-block">儲存</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/product_tag_category/index.blade.php
@extends('layouts.admin')

@section('content')
    @include('partials.breadcrumb', ['items' => [
        '產品標籤管理',
    ]])

    <table-component :fields="{{ $fields }}"
                     base-url="{{ route('product-tag-category.index', $customer) }}"
                     api-url="{{ route('api.admin.product-tag-category.get', $customer) }}"
                     api-token="{{ auth()->user()->api_token }}"
                     :can-copy="false">
    </table-component>
@endsection